# Generated by Django 5.2 on 2025-04-07 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="酒店名称"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="价格",
                    ),
                ),
                ("available", models.BooleanField(default=True, verbose_name="可预订")),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hotel_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="关联酒店"
                    ),
                ),
                (
                    "check_in",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="入住日期"
                    ),
                ),
                (
                    "check_out",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="退房日期"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        default="", max_length=100, verbose_name="预定者姓名"
                    ),
                ),
                (
                    "confirmation_number",
                    models.CharField(
                        default="", max_length=20, unique=True, verbose_name="确认号"
                    ),
                ),
                (
                    "guests_list",
                    models.JSONField(default=list, verbose_name="客人列表"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="总价",
                    ),
                ),
            ],
        ),
    ]
